apiVersion: v1
kind: Service
metadata:
  name: streamflix-service
  namespace: streamflix
  labels:
    app: streamflix
spec:
  selector:
    app: streamflix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP